# NumPy Fundamentals: Manipulating Matrices
Please follow the instructions and uncomment the skeleton code as necessary.

This assignment is due in addition to the small group assignment before the next class

In [3]:
import numpy as np

In [3]:
# Create a 3x3x3 np.array
my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
print(my_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


## Multidimensional Indexing

### Q.1 Print the value `2.0` from `my_array` using its index

In [4]:
print(np.argwhere(my_array==2))

[[1 0 0]
 [1 0 1]
 [1 0 2]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 2 0]
 [1 2 1]
 [1 2 2]]


#### Q.2 Use multidimensional slicing to print a 3x3 array that contains *all* values of `2` from `my_array`.

In [5]:
my_array[my_array == 2].reshape(3, 3)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

#### Q.3 Use multidimensional slicing to add `5` to every other element in `my_array` such that `print(new_array)` outputs

```python
[[[6. 1. 6.]
  [1. 6. 1.]
  [6. 1. 6.]]

 [[7. 2. 7.]
  [2. 7. 2.]
  [7. 2. 7.]]

 [[8. 3. 8.]
  [3. 8. 3.]
  [8. 3. 8.]]]
```

In [6]:

my_array = [[[1]],[[2]],[[3]]] * np.ones((3,3,3))
new_array = my_array


new_array += 5         
new_array += 5         
print(new_array)


[[[11. 11. 11.]
  [11. 11. 11.]
  [11. 11. 11.]]

 [[12. 12. 12.]
  [12. 12. 12.]
  [12. 12. 12.]]

 [[13. 13. 13.]
  [13. 13. 13.]
  [13. 13. 13.]]]


## Reshaping Matrices

#### Please refer to your notes on the `transpose`, `reshape`, and `flatten` methods to answer questions 4-6. 

#### Q.4 Create a 1D array from on `my_array`.

In [7]:
 my_1d_list = (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27)
 my_1d_array = np.array(my_1d_list)
 print(my_1d_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


#### Q.5 Create a 2D array from `my_array` that has 3 rows and 9 columns

In [8]:
my_2d_array = my_1d_array.reshape(3,9)
print(my_2d_array)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


#### Q.6 Create a new 3D array from `my_array` so that each 3x3 sub-array has at least one row with the values `[1, 2, 3]`.

In [20]:
my_array = my_1d_array
print(my_array)
my_3d_array = my_array.reshape(3,3,3)
my_3d_array.sort()
print(my_3d_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
